server.port=${SERVER_PORT:8080}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

# JWT
jwt.secret=MySuperLongAndSecureJwtSecretKey_1234567890_ABCDEF
jwt.expiration-ms=86400000
